export const products = [
  {
    id: "sku-001",
    name: "Daily Glow Cleanser",
    brand: "Lumina Labs",
    category: "Skincare",
    description: "Gentle cleanser untuk pemakaian harian.",
    price: 129000,
    currency: "IDR",
    imageUrl: "https://example.com/images/products/sku-001.jpg",
    affiliateUrl: "https://example.com/aff/sku-001",
    marketplace: "Shopee",
    availability: "in_stock",
    creatorRating: 4.7,
    communityRating: 4.5,
    tags: ["cleanser", "hydrating", "daily"],
    variants: [
      { id: "sku-001-100", label: "100ml", price: 129000, currency: "IDR" },
      { id: "sku-001-200", label: "200ml", price: 199000, currency: "IDR" },
    ],
  },
  {
    id: "sku-002",
    name: "Barrier Repair Serum",
    brand: "DermaNova",
    category: "Skincare",
    description: "Serum untuk memperkuat skin barrier.",
    price: 189000,
    currency: "IDR",
    imageUrl: "https://example.com/images/products/sku-002.jpg",
    affiliateUrl: "https://example.com/aff/sku-002",
    marketplace: "Tokopedia",
    availability: "in_stock",
    creatorRating: 4.8,
    communityRating: 4.6,
    tags: ["serum", "barrier", "niacinamide"],
    variants: [{ id: "sku-002-30", label: "30ml", price: 189000, currency: "IDR" }],
  },
  {
    id: "sku-003",
    name: "Matte Finish Sunscreen SPF50",
    brand: "Sunward",
    category: "Skincare",
    description: "Sunscreen ringan dengan hasil matte.",
    price: 99000,
    currency: "IDR",
    imageUrl: "https://example.com/images/products/sku-003.jpg",
    affiliateUrl: "https://example.com/aff/sku-003",
    marketplace: "TikTok Shop",
    availability: "low_stock",
    creatorRating: 4.6,
    communityRating: 4.4,
    tags: ["sunscreen", "spf50", "matte"],
    variants: [
      { id: "sku-003-50", label: "50ml", price: 99000, currency: "IDR" },
      { id: "sku-003-100", label: "100ml", price: 159000, currency: "IDR" },
    ],
  },
  {
    id: "sku-004",
    name: "Everyday Office Blazer",
    brand: "Form & Fit",
    category: "Fashion",
    description: "Blazer basic untuk style kantor.",
    price: 349000,
    currency: "IDR",
    imageUrl: "https://example.com/images/products/sku-004.jpg",
    affiliateUrl: "https://example.com/aff/sku-004",
    marketplace: "Lazada",
    availability: "in_stock",
    creatorRating: 4.5,
    communityRating: 4.3,
    tags: ["blazer", "office", "smart-casual"],
    variants: [
      { id: "sku-004-s", label: "Size S", price: 349000, currency: "IDR" },
      { id: "sku-004-m", label: "Size M", price: 349000, currency: "IDR" },
      { id: "sku-004-l", label: "Size L", price: 349000, currency: "IDR" },
    ],
  },
] as const;

export function findProduct(productId: string) {
  return products.find((product) => product.id === productId) ?? null;
}

